(1-c) Result page #4-BaharBazargan
Miladepour/SyntaxSquad-Project-Kunji pull request #15
Opened 2023-03-10 12:38 UTC by baharbazargan62

## Description

I have made the result page which includes table that received all information from the Json file and prepare table for filtering data which came from pre page 's data

## Related to

(1-c) Result page #4

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-03-10 20:51 UTC, EneVladMihai commented
Could you double check that the linked in the **Related to** points to the correct issue?

2023-03-11 01:38 UTC, KptCnyt approved these changes
All great, thank you

2023-03-12 23:15 UTC, baharbazargan62 commented
> Could you double check that the linked in the **Related to** points to the correct issue?

YES,I sort it out.

2023-03-13 21:49 UTC, EneVladMihai requested changes
Very minor things. Nice work, the compoent and filtering are very cleanly implemented.

2023-03-13 21:49 UTC, EneVladMihai commented on client/src/pages/result/Result.js
> +            <option  key={index}>{item}</option>
Very nice use of `Set`!
The `key` should be something that uniquely identifies the object. While the index is sometimes a viable option if there's no other in this case we can use the `item` itself.

2023-03-13 21:49 UTC, EneVladMihai commented on client/src/pages/result/Result.css
> +Button{
Is this used? If not better to remove as it will make the code harder to read in the future

2023-03-14 09:40 UTC, EneVladMihai commented on client/src/pages/result/Result.js
> +            <option key={index}>{item}</option>
Same thing about the `key` here

2023-03-14 09:53 UTC, baharbazargan62 commented on client/src/pages/result/Result.js
> +            <option key={index}>{item}</option>
It has done.

2023-03-14 10:01 UTC, EneVladMihai approved these changes

2023-03-14 10:18 UTC, merged