18 create user view page in frontend
Miladepour/SyntaxSquad-Project-Kunji pull request #28
Opened 2023-03-17 18:17 UTC by KptCnyt

## Description

#18 User view table nested in admin route, ngo_list, user_informations table with script

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] I have updated any documentation

2023-03-17 19:25 UTC, haroon-ali-dev requested changes

2023-03-17 19:25 UTC, haroon-ali-dev commented on client/src/pages/admin/UserView.js
> +                return <tr>
tr element needs a key prop. giving error in console.

2023-03-19 16:34 UTC, haroon-ali-dev approved these changes
Everything is working locally, the data is being displayed from the database.

2023-03-19 17:06 UTC, natyfromwonderland approved these changes
data works locally.

2023-03-20 12:10 UTC, closed without merging