30 adding user info to database
Miladepour/SyntaxSquad-Project-Kunji pull request #37
Opened 2023-03-21 10:08 UTC by baharbazargan62

## Naming Rules

#30/Adding user info to database /bahar

adding recaptcha

## Related to

#37

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-03-21 23:38 UTC, EneVladMihai reviewed
Looks good to me. Only suggestion from UX perspective would be not to show the ReCAPTCHA and form at the same time. We can show the form first, let them fill the data and when they click the "Next" button we show the ReCAPTHA and hide the form

2023-03-23 15:22 UTC, haroon-ali-dev approved these changes
Everything works great locally. ReCaptcha barrier works, user info is inserted into database correctly. All validation for front-end and back-end works fine.

2023-03-23 22:22 UTC, EneVladMihai requested changes
Good work. Added two comments to bring the code in line with common industry practices.

2023-03-23 22:22 UTC, EneVladMihai commented on server/routes/user.js
> +      res.json(result.rows[0]);
After successfully inserting something in the DB, it's standard to return a status of `201`.
Making this change will prob have an impact on this [line](https://github.com/Miladepour/SyntaxSquad-Project-Kunji/pull/37/files#diff-d2e54251fe00b6c1aa216984652dbe359d580b1379364133310be76e0250289bR66) as well.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

2023-03-23 22:22 UTC, EneVladMihai commented on client/src/components/UserForm.js
> +       sitekey="6LfUTRElAAAAAGygougsf9-TgpDcXrONCKzZGqJP"
This should be stored in an application variable. (e.g. the ones that start with `REACT_APP_`).

[See doc](https://create-react-app.dev/docs/adding-custom-environment-variables/)

2023-03-24 16:27 UTC, Miladepour approved these changes
I have finished my review.

2023-03-24 16:38 UTC, merged