50 update user form with clients feedback
Miladepour/SyntaxSquad-Project-Kunji pull request #54
Opened 2023-03-25 15:22 UTC by baharbazargan62

## Description

add 'Transgender' and 'Other' options to the gender dropdown list
qualification field should have the following options: 'Cannot read or write', '8th', '10th', '12th', 'Graduate', 'Postgraduate', 'Other'
case status should have the following options: 'Ongoing', 'Acquitted', 'Convicted'
pin code and email fields should be non compulsory: pin code should also be changed in the database and NOT have 'not null' requirement
## Related 
#50 

Fixes #1

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-03-25 18:55 UTC, Miladepour commented
I'm receiving error 400 (Bad Request) after submitting the form, are you done with these pull requests?

2023-03-27 08:54 UTC, baharbazargan62 commented
> I'm receiving error 400 (Bad Request) after submitting the form, are you done with these pull requests?

thank you Milad for checking this it has done know please check again

2023-03-29 10:25 UTC, natyfromwonderland commented
@Miladepour , are you still getting an error?

2023-03-29 10:36 UTC, Miladepour commented
> @Miladepour , are you still getting an error?

Yes, what about you?

2023-03-29 10:41 UTC, natyfromwonderland commented
> 

can you see what the error is? Is the pin code in your local database set to be NOT not null?

2023-03-29 10:52 UTC, Miladepour requested changes

2023-03-29 10:52 UTC, Miladepour commented on client/src/components/UserForm.js
> +            <option value="Transgender'">Transgender</option>
**<option value="Transgender**'**">** in this line there is one single quote extra which sends the wrong data to the database, 
Please change this.
"Transgender"

2023-03-29 10:53 UTC, Miladepour commented
> > 
> 
> can you see what the error is? Is the pin code in your local database set to be NOT not null?

Thanks, I fixed that on my database.

2023-03-29 20:42 UTC, Miladepour approved these changes
Thanks, Bahar.
I finished my review and tested it.

2023-03-29 21:43 UTC, natyfromwonderland approved these changes
Thanks Bahar! Could you please inform your team to update their local databases (pin code field shouldn't be not null) and there might be another pull request enhancement to check for phone and email format required for sending info functions.

2023-03-29 23:26 UTC, merged